### PR TITLE
Fixes sed usage on FreeBSD

### PR DESCRIPTION
**Pull request by jbenden**
This PR fixes sed usages on FreeBSD. Simple testing of sed usage was performed on Linux, so it may fully function on Linux too.

### CODE REVIEW

**Comment by greenrd** [comment]
Can you share a reproducible test case for the issues you fixed? It would be good for TopGit to have a test suite, and I guess this is as good a place to start as any.

**Comment by jbenden** [comment]
Would the shell test framework below work for you, as a Git submodule?

https://github.com/sstephenson/bats

**Comment by greenrd** [comment]
Yes, looks good to me.

**Comment by jbenden** [comment]
I have vendored BATS as a submodule, added a Makefile target to run the test (check target), and added a simple test.

**Comment by greenrd** [comment]
Thanks - but there seems to have been some confusion. What I meant was, can you share a test case that runs tg the same way you did, on some example git repository, and checks that it works? Then I will be able to run that test on both Linux and FreeBSD every time I make a change, to make sure I don't break tg on FreeBSD again.

**Comment by jbenden** [comment]
Writing a functional test is sort of not what I had in mind - it is just a typical workflow with TopGit.

TopGit on FreeBSD is now supported through the ports collection; see here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215050

**Comment by greenrd** [comment]
This version of TopGit is now unmaintained - please see https://github.com/mackyle/topgit for a newer version.

**Pull request closed without merging**
