### PR TITLE
make usage of $PAGER more POSIX-compatible

### LINKED ISSUE #36: tg help summary fails on when $PAGER contains a complex command string
`tg help summary` fails at [tg.sh, line 462](https://github.com/greenrd/topgit/blob/3f164dccbbbd8ba73139599fa91211c8adc5dcca/tg.sh#L462) when `PAGER` contains a complex command strings like e.g. `less -R`.

According to [POSIX's man(1)](http://www.unix.com/man-page/posix/1/man/) `PAGER` may contain _any string acceptable as a command_string operand to the sh -c command_.

A possible solution to this problem would be to eval `TG_PAGER` or call it with `sh -c "$TG_PAGER"`.

Reference: http://lists.science.uu.nl/pipermail/nix-dev/2014-September/014244.html

### PR DESCRIPTION
**Pull request by 4z3**
Fixes #36

### CODE REVIEW

**Comment by Profpatsch** [comment]
please merge.

**Comment by greenrd** [comment]
Have you tested it with a value of `PAGER` that contains space(s)? I'm surprised that this PR would work.

**Comment by Profpatsch** [comment]
Just tested it with `less -R`, works.

**Comment by greenrd** [comment]
I've committed a different fix for this problem.

**Comment by 4z3** [comment]
Your [fix](https://github.com/greenrd/topgit/commit/736f664f2e2f7f2c14bae46fb9053db07e65c8e9) isn't [POSIX-compatible](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/man.html#tag_20_77_08) and will break when `TG_PAGER` defaults to the value of `PAGER` because:

> Any string acceptable as a command_string operand to the sh -c command shall be valid.

Furthermore, the quotes this patch introduces aren't necessary. See [variable assignment](http://pubs.opengroup.org/onlinepubs/009604499/basedefs/xbd_chap04.html#tag_04_21) and [word expansion](http://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_06).

**Comment by greenrd** [comment]
You are right about the quotes, but
1. your links don't explain why - [this](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09_01) is the correct link.
2. this mistake is all over the codebase - I have raised [another issue](https://github.com/greenrd/topgit/issues/56) for that

I don't understand your other comments. Please give a reproducible test case and state the operating system.

**Pull request closed without merging**
